name: CI-Forbidden Content Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-chinese:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Chinese check script
        run: |
          python CHECKING/no_chinese.py
          python CHECKING/no_print.py
